#端口号
server:
  port: 7004
# Spring配置
spring:
  profiles:
    active: dev
  application:
    name: springcloud
  cache:
    type: caffeine
    cache-names: outLimit,notOutLimit,myCache,parmDicCatche,projBaseCatche
    caffeine:
      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=5s,refreshAfterWrite=7s
# eureka配置
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
#rocketMQ配置
rocketmq:
  topic: JD_MFS_MESSAGE
  group: my-group
  sendTimeout: 5000
  name-server: 140.143.124.166:9876
  producer:
    group: my-group
