#端口号
server:
  port: 7004

spring:
  application:
    name:  eureka-zuul-7004

#eureka配置
eureka:
  instance:
    #注册中心ip地址
    hostname: eureka7004.com
  client:
    #是否注册到eureka
    #registerWithEureka: false
    #是否检测服务信息
    #fetchRegistry: false
    #注册地址
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/,http://127.0.0.1:7003/eureka/

#API网关配置
zuul:
  #路由配置
  routes:
    producer:
      #响应的路径
      path: /producer/**
      #重定向到的服务（根据服务id名称从注册中心获取服务地址）
      serviceId:  eureka-7001